config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  resources :consumidores
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/consumidor.rb
class Consumidor < ApplicationRecord
  validates :nome, :telefone, :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/consumidores_controller.rb
class ConsumidoresController < ApplicationController
  before_action :set_consumidor, only: %i[ show edit update destroy ]

  def index
    @consumidores = Consumidor.all
  end

  def show
  end

  def new
    @consumidor = Consumidor.new
  end

  def edit
  end

  def create
    @consumidor = Consumidor.new(consumidor_params)

    respond_to do |format|
      if @consumidor.save
        format.html { redirect_to consumidor_url(@consumidor), notice: t('activerecord.notices.consumidor.created') }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @consumidor.update(consumidor_params)
        format.html { redirect_to consumidor_url(@consumidor), notice: t('activerecord.notices.consumidor.updated') }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /consumidores/1 or /consumidores/1.json
  def destroy
    @consumidor.destroy

    respond_to do |format|
      format.html { redirect_to consumidores_url, notice: "Consumidor was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_consumidor
      @consumidor = Consumidor.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def consumidor_params
      params.require(:consumidor).permit(:nome, :telefone, :email)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/consumidores_helper.rb
module ConsumidoresHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/application/_flash.html.erb
<% if flash.any? %>
  <div class="flash-outer" id="flashMessage" data-controller="removals"
       data-action="animationend->removals#remove">
    <% flash.each do |key, notice| %>
      <div class="relative h-10 mb-5">
        <div class="absolute right-0 top-1/2 transform -translate-y-1/2 z-20">
          <div class="py-2 px-3 bg-green-50 text-green-500 font-medium rounded-lg inline-block max-w-xs">
            <%= notice %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/application/_navbar.html.erb
<nav class="mx-auto flex max-w-7xl items-center justify-between p-6 lg:px-8" aria-label="Global">
    <div class="flex lg:flex-1">
      <a href="#" class="flex gap-4 items-center -m-1.5 p-1.5", id= "logo">
        <i class="fa-solid fa-lines-leaning text-blue"></i>
        <p><%= link_to 'APP SALES', root_path, class: "flex items-center gap-x-1 text-md font-semibold leading-6 text-gray-900 color-blue px-3" %></p>
      </a>
    </div>
    <div class="flex lg:hidden">
      <button type="button" class="-m-2.5 inline-flex items-center justify-center rounded-md p-2.5 text-gray-700">
        <span class="sr-only">Open main menu</span>
        <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
          <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
        </svg>
      </button>
    </div>
    <div class="hidden lg:flex lg:gap-x-12">

      <%= link_to 'Vendas', root_path, class: "text-md font-semibold leading-6 text-gray-900" %>
      <%= link_to 'Caixa', root_path, class: "text-md font-semibold leading-6 text-gray-900" %>
      <%= link_to 'Clientes', consumidores_path, class: "text-md font-semibold leading-6 text-gray-900" %>
    </div>
    <div class="hidden lg:flex lg:flex-1 lg:justify-end">
      <a href="#" class="text-sm font-semibold leading-6 text-gray-900">Log in <span aria-hidden="true">&rarr;</span></a>
    </div>
  </nav>

app/views/consumidores/_consumidor.html.erb
<div id="<%= dom_id consumidor %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Nome:</strong>
    <%= consumidor.nome %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Telefone:</strong>
    <%= consumidor.telefone %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Email:</strong>
    <%= consumidor.email %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Mostrar cliente", consumidor, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Editar cliente', edit_consumidor_path(consumidor), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/consumidores/_form.html.erb
<%= form_with(model: consumidor, class: "contents") do |form| %>
  <% if consumidor.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(consumidor.errors.count, "error") %> - cliente não foi salvo:</h2>

      <ul>
        <% consumidor.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :nome %>
    <%= form.text_field :nome, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :telefone %>
    <%= form.text_field :telefone, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :email %>
    <%= form.text_field :email, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit 'Salvar', class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/consumidores/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-2xl">Editar cliente</h1>

  <%= render "form", consumidor: @consumidor %>

  <%= link_to "Show this consumidor", @consumidor, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to consumidores", consumidores_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/consumidores/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-2xl">Clientes</h1>
    <%= link_to 'Novo cliente', new_consumidor_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="consumidores" class="flex flex-col w-96">
    <% @consumidores.each do |cliente| %>
      <div class="flex justify-between items-center py-3">
        <p><%= link_to cliente.nome, cliente %></p>
        <%= link_to 'Detalhes', cliente, class: "ml-2 rounded-lg py-2 px-3 bg-gray-100 inline-block font-medium" %>
      </div>
    <% end %>
  </div>
</div>

app/views/consumidores/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-2xl">Novo cliente</h1>

  <%= render "form", consumidor: @consumidor %>

  <%= link_to 'Todos clientes', consumidores_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/consumidores/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">

    <%= render @consumidor %>

    <%= link_to 'Editar cliente', edit_consumidor_path(@consumidor), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Excluir cliente', consumidor_path(@consumidor), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Todos clientes', consumidores_path, class: "ml-2 rounded-lg py-3 px-5 bg-blue inline-block font-medium" %>
  </div>
</div>

app/views/home/index.html.erb
<h1>Bem vindo</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <script src="https://cdn.tailwindcss.com"></script>
  <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
  <%= stylesheet_link_tag "tailwind", "data-turbo-track": "reload" %>
  <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
  <%= javascript_include_tag 'application', 'data-turbo-track': 'reload' %>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
  <title>App-Sales</title>
</head>
<header class="bg-white">
  <%= render 'navbar' %>
</header>

<body class="min-h-screen bg-gray-light">
  <div class="container mx-auto p-10">
    <div class="relative h-0">
      <div class="flash">
        <%= render "flash" %>
      </div>
    </div>
    <%= yield %>
  </div>
</body>
</html>